version: '3.1'

services:
  redmine:
    image: redmine:5.1
    ports:
      - 3000:3000
    env_file:
      - ./envs/redmine.env
    volumes:
      - redmine-files:/usr/src/redmine/files
    links:
      - redmine-db
  redmine-db:
    image: postgres:16-alpine
    env_file:
      - ./envs/redmine.env
    volumes:
      - redmine-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redash-server:
    image: redash/redash:10.1.0.b50633
    command: server
    ports:
      - 5000:5000
    env_file:
      - ./envs/redash.env
    links:
      - redash-redis
      - redash-db
      - redmine-db
  redash-worker:
    image: redash/redash:10.1.0.b50633
    command: worker
    env_file:
      - ./envs/redash.env
    links:
      - redash-redis
      - redash-db
      - redmine-db
  redash-redis:
    image: redis:7-alpine
  redash-db:
    image: postgres:16-alpine
    env_file:
      - ./envs/redash.env
    volumes:
      - redash-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redmine-files:
  redmine-db:
  redash-db:

